### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows"

### ISSUE THREAD

**Issue by gaetancollaud** [thunderbug1/Spherebot-Host-GUI#20]
Hello,

When I start the Spherebot_UI.exe from the release 2.0 I got this message : 

> This application failed to start because it could not find or load the Qt platform plugin "windows". 
> Reinstalling the application may fix this problem.

I'm on Windows 7 64bits.

I read [this blog post](http://www.tripleboot.org/?p=138), and I think a DLL is missing.

Regards

**Comment by thunderbug1** [comment]
Yes I had this problem with other dll´s too.
As I can´t reproduce the error you have to fix it but it is not hard. 

Use this http://www.dependencywalker.com/ to analyse which dll is missing.
Install Qt on your machine and then search the missing dll in the folder structure of the Qt installation and copy the dll to the folder where the UI-exe is to the other dll´s. 
That should fix it ;)

maybe you could upload the dll to github when you are done to keep others from running into the same problem.
