### ISSUE TITLE
Commands left out / Maybe not resend

### ISSUE THREAD

**Issue by JamesT42** [thunderbug1/Spherebot-Host-GUI#21]
Hi!
So I tried the latest version.
But still i have severe problems with the GUI.
I think that the GUI doesn't handle "rs" (resend) requests correctly. In my case that leads mostly to missing pen up/down commands, resulting in missing lines or drawing a line while positioning the egg.
I know its not a Hardware problem, because I can print the same gcode file with pronterface with 0 trouble.

**Comment by thunderbug1** [comment]
I think I have found the bug. The Serial.flush() function of the Qt-library does not work correctly and all commands were sent twice. Because of that the wrong line was resent when requested. It should be fixed now.
