### ISSUE TITLE
Steppers/ Servo not responding to commands in Spherebot UI

### ISSUE THREAD

**Issue by Flaksi** [thunderbug1/Spherebot-Host-GUI#23]
Hi, 

I made a Sherebot with my Arduino Mega and Ramps 1.4. Changed the config files pin mappings. I am able to send G-code commands to it fine through Arduino Serial monitor (NL&CR enabled, with 115200 baud rate). Spherebot fw version is 2.1
When I use Spherebot UI it connects to the same port (Successfully Connected to Spherebot Flashes) and I can hear the servo making a tiny movement sound. But sending manually any commands or sending a G-code file does not produce any actions with the steppers or servo. I guess there must be something really trivial now that is wrong in my setup ?

Could you please suggest any things that I should check out.

Below is a copy form the two successfully executed commands with the serial monitor:

---

Spherebot 2.1
ok G1 X20 Y300 F1500

ok 

ok M300 S15

ok 

---

Br, Marko

**Comment by kolaha99** [comment]
Spherebot UI don't understand M-Code, even CR LN without any attention.
 
G-Code file:

`G21 (All units in mm)`
`(Start cutting path id: path10115)`
`M300 S100(Change tool to Cylindrical cutter)`
`G00 X875.495010 Y146.484750`
`M300 S115(Penetrate)`
`G01 X882.678133 Y146.484750 F400.000000`

Tranceived Data window:

`G01 X882.678133 Y146.484750 F400.000000`
`G00 X875.495010 Y146.484750M300 S115`
`M300 S100`
`G21`

Received Data window:

`ok:G01 X882.678133 Y146.484750 F400.000000`
`ok:M300 S100`
`ok:G21`
`Ready`

**Comment by thunderbug1** [comment]
It seems as if there is something wrong with your wiring or pin assignment. The UI seems to work correctly.
