### ISSUE TITLE
Adaptation

### ISSUE THREAD

**Issue by elgrandandy** [thunderbug1/Spherebot-Host-GUI#25]
Could this be adapted to draw on a cylindrical objects?

**Comment by JamesT42** [comment]
Maybe look into something like this
https://hackaday.com/2018/11/25/mug-o-matic-plots-on-coffee-mugs/
https://hackaday.com/2013/03/15/mug-plotter-based-on-the-eggbot/
https://www.instructables.com/id/Mug-Plotter/

**Comment by elgrandandy** [comment]
Thanks
